services:
  - type: web
    name: geohunt-server
    env: node
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
    nodeVersion: 18.19.1 